### ISSUE TITLE
Example video player

### ISSUE THREAD

**Issue by ghost** [manijak/nativescript-youtube-parser#1]
Hello everyone , i was trying to implement this plugin and i can get return a URL but when i put the URL in a player does not reproduce the video, someone can help me ?

i doing this
let url:
youtubeParser.getURL('https://youtu.be/C_vqnySNhQ0', { quality: 'medium', container: 'mp4' })
    .then(function (urlList) {
        console.log("YouTube mp4 video url: ", urlList[0].url);
        url=urlList[0].url; -----> i wanna put this in <video></video>
    }
);

< VideoPlayer
      src="{{url}}"
      autoplay="false"
      controls="true" 
      height="300" >< / VideoPlayer >

using nativescript-videoplayer 

Thanks in advance

**Comment by manijak** [comment]
Hmmm, I'm also using the `nativescript-videoplayer` in my app, and it works fine both in iOS and Android. Are you by any chance using Angular2?

Would help if you posted full code example. When I find time, I will create a demo app and add it to the git.

PS. You did expose the `url` as a observable? Based on your example I would:
```
url=urlList[0].url;
pageData.set("url", url);
```
Where `pageData` is the observable added to the page bindingContext.

**Comment by ghost** [comment]
Yes, I'm using Angular2

Checking the code everything was working well, it was just that some videos do not play them, I never thought to try another.

Do you know under what circumstances the video does not play? Or if it is something that could determine through the URL?

**Comment by manijak** [comment]
You can try playing the url directly in your browser or in VLC, just to test it. Otherwise it could be something with the videoplayer plugin and Angular2

**Comment by ghost** [comment]
After some tests I found the issue.

The problem isn't the video player, is the URL return by the plugin, in some cases dont contain the parameter `signature` and only the urls that contain this parameter can be played

some idea?

**Comment by manijak** [comment]
That is strange... could you provide an example of the video that is not working?
