### ISSUE TITLE
urlList[0].url IS UNDEFINED VALUE

### ISSUE THREAD

**Issue by nrbn** [manijak/nativescript-youtube-parser#2]
Hi,

I try to excute this code and i do not get video url. It does not go inside youtubeparser.geturl function.
Sure I have var youtubeParser = require ("nativescript-youtube parser");

```
var url;
    youtubeParser.getURL('https://youtu.be/C_vqnySNhQ0', { quality: 'medium', container: 'mp4' })
        .then(function (urlList) {
                url=urlList[0].url; 
                alert(url);
        }
    );

    
```

**Comment by manijak** [comment]
Hmm... Could you try with the following url format:
`https://www.youtube.com/watch?v=C_vqnySNhQ0`

**Comment by nrbn** [comment]
It is same. It does not execute geturl function.

**Comment by nrbn** [comment]
I forgot to tell you, when i first time added this plugin, plugin was not recognized. I manually added it on package.json, iam not sure i did it right way.

 "dependencies": {
    "nativescript-admob": "^1.3.2",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-videoplayer": "^3.0.8",
    **"nativescript-youtube-parser": "^1.0.0",**  
    "tns-core-modules": "~3.0.0"
  },
`

**Comment by nrbn** [comment]
![0-02-05-99e765b9b9c8fde5df406e3618149c7913d0fc87f2a7b3d11df9a35b8521047f_full](https://user-images.githubusercontent.com/10879727/27963035-04220e32-6334-11e7-8177-8937bdadb8ff.jpg)

**Comment by nrbn** [comment]
Do you have any working project i can clone?

**Comment by manijak** [comment]
Ok found an issue on Android that would cause it not to work. Published a fix just now to npm. 

But. There is an issue with the videoplayer plugin that you are using. It seems not to render when running the latest tns-core-modules. I had to downgrade tot 3.0.1 for it to work. 

Works fine in iOS.

**Comment by nrbn** [comment]
Thank you Manijak, its working now 👍
