### ISSUE TITLE
Some youtube video not working!!

### ISSUE THREAD

**Issue by nrbn** [manijak/nativescript-youtube-parser#3]
Hi,

Some youtube video links get 404. But the video exists on youtube. When I visit the urlList[0].url I get this message:
Access to r6---sn-5aupcvm-vnae.googlevideo.com was denied

You don't have authorization to view this page.
HTTP ERROR 403

Why?

**Comment by manijak** [comment]
I cannot answer this, the parser works fine and fetches the raw url for you, but what happens after that is unknown to me. Sorry.
