### ISSUE TITLE
The live youtube is not working

### ISSUE THREAD

**Issue by nrbn** [manijak/nativescript-youtube-parser#4]
I have tried to get live video from youtube but it does not work.
Example this url:

https://www.youtube.com/watch?v=ITmaIoNIZZQ

Does this code not get mp4 of live video?

**Comment by manijak** [comment]
This plugin is based on another npm plugin and is basically just a simple HTML parser. It opens a certain youtube page and tries to parse out the raw video url. No guarantee that it will work, and will probably stop working all together in the future. 

**I wouldn't recommend using this plugin in any production application. This could be treated as illegal by Google and YouTube,  and your application might be suspended.**

**No further development or maintenance will be done on this plugin.**
