### ISSUE TITLE
Not returning valid urls

### ISSUE THREAD

**Issue by alexanderpivanov** [manijak/nativescript-youtube-parser#6]
Am using the parser like that:

youtubeParser.getURL('https://youtu.be/C_vqnySNhQ0', { quality: 'medium', container: 'mp4' })
    .then(function (urlList) {
        console.log("YouTube mp4 video url: ", urlList[0].url);
    }
);

for this particular link there is no problem, but for those it is not working.

https://youtu.be/odEMPeZnY0o 
parser return link: https://r2---sn-nv47ln7k.googlevideo.com/videoplayback?dur=1069.650&lmt=1504515872007393&key=yt6&ipbits=0&initcwndbps=5825000&id=o-APETKkQMWHF4tvxT6tkURQ0mGbyP7Mpz5Vjv3cfO6UpL&ratebypass=yes&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&ip=193.194.156.5&gir=yes&ei=vmTLWYW3DoqRWqXAoMAE&ms=au&mt=1506501649&itag=18&pl=24&mv=m&mn=sn-nv47ln7k&expire=1506523422&clen=83476198&mime=video%2Fmp4&requiressl=yes&source=youtube&mm=31

https://youtu.be/435vu9mI1_g 
parser return link: https://r3---sn-nv47ln7r.googlevideo.com/videoplayback?ipbits=0&mime=video%2Fmp4&dur=823.054&itag=18&gir=yes&ip=193.194.156.5&ratebypass=yes&mn=sn-nv47ln7r&source=youtube&mm=31&mv=m&pl=24&mt=1506501827&ms=au&id=o-APfSaqOS_PgIXUt8ixM6QNekpn7hkYgdru_q8aCje_PS&ei=NmXLWceQMY-LWteSvvgI&initcwndbps=4111250&key=yt6&requiressl=yes&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&lmt=1504515010343523&expire=1506523542&clen=54848702

Here are some that are working: 
https://youtu.be/LuSouIhZ58I
parser return link: https://r6---sn-nv47lne6.googlevideo.com/videoplayback?dur=945.307&lmt=1501231958078326&key=yt6&ipbits=0&initcwndbps=5825000&id=o-AHeWpM4Apew4vK08Lw00JLhcAcOZUVQnIDrVd08cS2y9&mn=sn-nv47lne6&ratebypass=yes&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&ip=193.194.156.5&gir=yes&ei=pGXLWe6oPMGXW7OblTg&ms=au&mt=1506501941&itag=18&pl=24&mv=m&expire=1506523653&mime=video%2Fmp4&clen=73036751&requiressl=yes&source=youtube&signature=C46323B0DD397BE3985CAB30FAD6E626D5FF9E08.76D201C4DCB18EDBC9C2E963EE56DDF1ED26F0EB&mm=31

https://youtu.be/hrFGRJNqQZM
parser return link: https://r1---sn-nv47lne6.googlevideo.com/videoplayback?ei=IGfLWfWJC5n0WJbYu_gG&initcwndbps=3988750&dur=987.149&expire=1506524032&ipbits=0&id=o-AMYyFBbljG5hg2wc486Bp6Ffh3CY_0tBeqJjBVNLMkV6&mime=video%2Fmp4&pl=24&mm=31&mn=sn-nv47lne6&ms=au&mt=1506502363&gir=yes&ip=193.194.156.5&requiressl=yes&mv=m&ratebypass=yes&signature=93D34E3EC1BCD7ED5D8CD622C4284E215C1E02D1.14EE01708F5A94BF53BFB2152179FD10B3E8624E&itag=18&key=yt6&lmt=1501492762260468&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&source=youtube&clen=85955328

Why they are not working?

**Comment by manijak** [comment]
Why some links work and some don't, I have no idea. This plugin is based on another npm plugin and is basically just a simple HTML parser. It opens a certain youtube page and tries to parse out the raw video url. No guarantee that it will work, and will probably stop working all together in the future. 

**To be honest I wouldn't recommend using this plugin in any production application. This could be treated as illegal by Google and Youtube,  and your application might be suspended.**

**No further development or maintenance will be done on this plugin.**

**Comment by alexanderpivanov** [comment]
Thank you for explaining this :) I used other youtube plugin.
